// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW1CQCoqK94D8m0sP4Ge5PwJxul32Y_zc',
    appId: '1:324123347818:web:d9ad7aee3259e7055df313',
    messagingSenderId: '324123347818',
    projectId: 'pandoo-64617',
    authDomain: 'pandoo-64617.firebaseapp.com',
    storageBucket: 'pandoo-64617.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAcAKHMbKvoc72Mid466lMu6j19ZUwhKw',
    appId: '1:324123347818:android:5b97e3335b0f117c5df313',
    messagingSenderId: '324123347818',
    projectId: 'pandoo-64617',
    storageBucket: 'pandoo-64617.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEgZ97yQB-B8QP2fuI4XGR1FPiuFzFNZ8',
    appId: '1:324123347818:ios:9728ed7d7eef49d85df313',
    messagingSenderId: '324123347818',
    projectId: 'pandoo-64617',
    storageBucket: 'pandoo-64617.firebasestorage.app',
    iosBundleId: 'com.example.pandoo',
  );
}
